name: Build
on:
  workflow_call:
jobs:
  main:
    name: HTML
    runs-on: ubuntu-22.04
    steps:
      - run: mkdir ~/static
      - name: Cache HTML
        uses: actions/cache@v3
        with:
          path: ~/static
          key: ${{ github.run_id }}
      - uses: actions/checkout@v3
      - name: Static HTML
        run: |
          npx respec --localhost --src index.html --out ~/static/snapshot.html