name: Publish
on:
  workflow_call:

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    steps:
      - uses: actions/checkout@v4
      - name: Recover HTML
        uses: actions/cache@v4
        with:
          path: ~/static
          key: ${{ github.run_id }}
      - name: Gather files
        run: |
          rm -f *.md *.html
          mv ~/static/* ./
          mv snapshot.html index.html
          mkdir content
          shopt -s extglob
          mv !(content) content
      - name: Commit release
        run: |
          git add -A
          git config user.name "GitHub Action"
          git config user.email "deploy-bot@geonovum.nl"
          git diff-index --quiet HEAD || git commit -m "Automated Release"
          git push

  deploy:
    name: Deploy to GitHub Pages
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    runs-on: ubuntu-22.04
    needs: release
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
